### ISSUE TITLE
g700s advice

### ISSUE THREAD

**Issue by reyqn** [andyvorld/LGSTrayBattery#10]
Hi, I'm trying to get the battery status from my logitech g700s, and stumbled through here while searching how to do so.
If I understand correctly, the g700s although from 2013 still uses hid++ 1.0, so it's not compatible with LSGTrayBattery.
Am I out of luck here? And if so, from your experience developing this, do you have some information that could help me develop something to get the battery status from my g700s?

**Comment by andyvorld** [comment]
Sure,
there is some documentation on hid++ 1.0 here, https://lekensteyn.nl/files/logitech/logitech_hidpp10_specification_for_Unifying_Receivers.pdf

I also used Solaar as a base of reverse engineering the hid++ 2.0 protocol, it should help with the hid++ 1.0.
Specficially this file https://github.com/pwr-Solaar/Solaar/blob/master/lib/logitech_receiver/hidpp10.py

**Comment by reyqn** [comment]
Thanks! I'll go ahead and close the issue since it's not related to your software. Have a nice day.
