### ISSUE TITLE
[FEATURE REQUEST] Logging battery level to file on disk

### ISSUE THREAD

**Issue by propiro** [andyvorld/LGSTrayBattery#107]
Hello,
I'd like to request a feature to log battery level (be it whole percentages, or fractions of percentages) to a file, with date. I'd like to monitor how long my mouse lasts on one battery charge, including how much I use it (since mine lasts 4-5 days, and friends have theirs for 2-3 weeks, ALLEGEDLY).

**Comment by andyvorld** [comment]
I don't think this is that core of a feature to be implemented in this program, given that there is the http server that can act as an endpoint for the logs.

For example a simple python script can just poll the endpoint and write it out to a file like the following,

```
import time
import urllib.request
import xml.etree.ElementTree as ET

LOG_FILE = './device.log'

SERVER = 'localhost:12321'
DEVICE_ID = 'dev00000000'

while True:
    with open(LOG_FILE, '+a') as file:
        f = urllib.request.urlopen(f'http://{SERVER}/device/{DEVICE_ID}')
        root = ET.fromstring(f.read().decode('utf-8'))

        last_update = root.find('last_update').text
        percent = root.find('battery_percent').text
        file.write(f'{last_update}, {percent}\n')
        file.flush()

    time.sleep(60)
```

Ill leave this open for now to see if there is any need for something like this. As I would think a customised script like above is more useful than a predetermined on by me.

**Comment by buffalodragon** [comment]
Actually, this is perfect.

There is another program (timschneeb/GalaxyBudsClient) that has a battery tracking feature. Simply plots battery percentage vs. time, as well as some other features.

![image](https://github.com/user-attachments/assets/d0ec21ba-4837-410c-93f9-567933acd0de)
![image](https://github.com/user-attachments/assets/4ecf57a3-6e80-4361-b67c-45c194f838be)
![image](https://github.com/user-attachments/assets/ea57aefe-112c-422b-b593-27c386c17460)

**Comment by buffalodragon** [comment]
And thank you for your sample code. I've modified it to output all my devices, along with voltage values (looks like voltage values don't work, only shows 0.00). I'll be able to generate graphs on top of it, perfect! I have additionally added in a "time_now" value, primarily for graphing, as the "last_update" only appears to change when the battery % changes.

Python code, standard libraries:

```
import time
from datetime import datetime
import urllib.request
import xml.etree.ElementTree as ET

SERVER = 'localhost:12321'
HEADSET_ID = 'dev00000000'
MOUSE_ID = 'dev00000001'
KEYBOARD_ID = 'dev00000002'

LOG_FILE = './device.log'

while True:
    with open(LOG_FILE, '+a') as file:

        f = urllib.request.urlopen(f'http://{SERVER}/device/{MOUSE_ID}')
        root = ET.fromstring(f.read().decode('utf-8'))

        time_now = datetime.now().strftime("%d/%m/%Y %H:%M:%S")

        device = root.find('device_name').text
        percent = root.find('battery_percent').text
        voltage = root.find('battery_voltage').text
        mileage = root.find('mileage').text
        last_update = root.find('last_update').text
        file.write(f'{device}, {time_now}, {last_update}, {percent}, {voltage}, {mileage}\n')

        f = urllib.request.urlopen(f'http://{SERVER}/device/{KEYBOARD_ID}')
        root = ET.fromstring(f.read().decode('utf-8'))

        device = root.find('device_name').text
        percent = root.find('battery_percent').text
        voltage = root.find('battery_voltage').text
        mileage = root.find('mileage').text
        last_update = root.find('last_update').text
        file.write(f'{device}, {time_now}, {last_update}, {percent}, {voltage}, {mileage}\n')

        f = urllib.request.urlopen(f'http://{SERVER}/device/{HEADSET_ID}')
        root = ET.fromstring(f.read().decode('utf-8'))

        device = root.find('device_name').text
        percent = root.find('battery_percent').text
        voltage = root.find('battery_voltage').text
        mileage = root.find('mileage').text
        last_update = root.find('last_update').text
        file.write(f'{device}, {time_now}, {last_update}, {percent}, {voltage}, {mileage}\n')

        file.flush()

    time.sleep(60)
```

**Comment by propiro** [comment]
> And thank you for your sample code. I've modified it to output all my devices, along with voltage values (looks like voltage values don't work, only shows 0.00). I'll be able to generate graphs on top of it, perfect! I have additionally added in a "time_now" value, primarily for graphing, as the "last_update" only appears to change when the battery % changes.
[...]
Hey, I've got a notification about your reply - Im using windows10, can you elaborate a bit more how can I achieve battery logging to a file?

**Comment by buffalodragon** [comment]
> > Hey, I've got a notification about your reply - Im using windows10, can you elaborate a bit more how can I achieve battery logging to a file?

If you know how to run Python, it's pretty simple. Copy & paste the code I've responded with above (https://github.com/andyvorld/LGSTrayBattery/issues/107#issuecomment-2495670568), paste it into a text document, and save it as a .py file. Run it & it will output a 'device.log' file, which you can open in Notepad. This is what my output looks like. Later, I will be making a different script that reads this data to output on a graph.

![image](https://github.com/user-attachments/assets/b88f8f9e-7558-4f6f-9a81-b7945086fbd0)

If you don't know how to use or run Python... well, I can somewhat briefly guide you.

i) Install Python: https://www.python.org/downloads/
ii) Get an IDE (I use Pulsar), or just save the code I mentioned above in a text document. An IDE basically makes the code "look nice" while you type it out
![image](https://github.com/user-attachments/assets/22af4fc9-a6f5-415d-881f-69efd6015dfc)
iii) Run it via CMD while LGSTray is open. You will need to navigate to where the .py file is saved, so it can run. Don't close the CMD window, otherwise the execution stops. To stop it manually, use `CTRL + C`, or close out the window.
![image](https://github.com/user-attachments/assets/499ae768-557b-4bc4-8d49-2bd423113b4d)

**Comment by propiro** [comment]
> > > Hey, I've got a notification about your reply - Im using windows10, can you elaborate a bit more how can I achieve battery logging to a file?
> 
> If you know how to run Python, it's pretty simple. Copy & paste the code I've responded with above ([#107 (comment)](https://github.com/andyvorld/LGSTrayBattery/issues/107#issuecomment-2495670568)), paste it into a text document, and save it as a .py file. Run it & it will output a 'device.log' file, which you can open in Notepad. This is what my output looks like. Later, I will be making a different script that reads this data to output on a graph.
>[...]


Thank you very much for thorough explanation, I've managed to make it work in python, and after that, I've just implemented it as a template sensor in my home assistant (that was end goal I wanted to achieve, I just needed some information about how you got to this point)

I'll be closing this topic as my issue/request has been fullfilled.

All the best,
A.
