### ISSUE TITLE
Crashing on G502 Lightspeed XML Import

### ISSUE THREAD

**Issue by SkilledAlpaca** [andyvorld/LGSTrayBattery#11]
I have a G502 Wireless. When I run the [LGSTrayBattery_GHUB_dump ](https://github.com/andyvorld/LGSTrayBattery_GHUB_dump) tool and move the generated file, the following happens. 

While the mouse is plugged in charging I get this message. 
![image](https://user-images.githubusercontent.com/26860324/102981602-0d25fb00-44be-11eb-82ef-4347996ffafd.png)

When the mouse is purely wireless, the app crashes on startup. [Crashlog.log](https://github.com/andyvorld/LGSTrayBattery/files/5734384/Crashlog.log)

Generated XML: [46D_407F.xml.txt](https://github.com/andyvorld/LGSTrayBattery/files/5734401/46D_407F.xml.txt)

**Comment by andyvorld** [comment]
Sorry about the delay, I am however away from my dev pc for christmas and the new year, so I would not be able to push any fixes, however the issue is quite easy as rename the generated folder from `46D_407F.xml.txt` to `46D_407F.xml`

**Comment by SkilledAlpaca** [comment]
Thank you for the reply. The `46D_407F` file generated as an XML file. I changed it to `.txt` so I could attach it to the issue. 

I tried out the GHUB variant and it's working out of the box no issues with my G502.

**Comment by andyvorld** [comment]
Hey sorry for the late reply, but I think I found the problem from your initial post.
It seems like the xml file was not formatted in the proper xml syntax, leading the program to crash.

I have attached a correctly formatted version for you if you still need it.

[46D_407F.xml.txt](https://github.com/andyvorld/LGSTrayBattery/files/5975503/46D_407F.xml.txt)

Likewise remove the .txt file extension.

**Comment by SkilledAlpaca** [comment]
This one works! Is this possibly a bug with the dump tool not formatting the XML file correctly?

Also I can open another request, but this one doesn't seem to have a "Start with Windows" option.

**Comment by andyvorld** [comment]
Sorry for the late update again, turns out windows had a weird quirk with auto starting programs and their working directory, which I had to fix.

[I have released a new version with the option to auto start now ](https://github.com/andyvorld/LGSTrayBattery/releases/tag/v1.0.6)
