### ISSUE TITLE
macOS Compatibility

### ISSUE THREAD

**Issue by WinterCabbage** [andyvorld/LGSTrayBattery#12]
Is it possible to run LGSTrayBattery on macOS? I'm looking so long for a light-weight program to check battery level of logitech mouse on macOS.

**Comment by huanga2** [comment]
Sorry, I wouldn't have the capabilities to find out, as I don't have a macOS device to even develop on. Further the libraries and framework used for this project is heavily tied to Windows.
However, like Solaar the opensource linux alternative to Logitech's program, it should be possible to write a similar program in macOS, but as it stands I fell like it will be a non-trivial task for me to port the existing program.

**Comment by andyvorld** [comment]
Sorry, I wouldn't have the capabilities to find out, as I don't have a macOS device to even develop on. Further the libraries and framework used for this project is heavily tied to Windows.
However, like Solaar the opensource linux alternative to Logitech's program, it should be possible to write a similar program in macOS, but as it stands I fell like it will be a non-trivial task for me to port the existing program.
