### ISSUE TITLE
Uknown Hard Error

### ISSUE THREAD

**Issue by realgooseman** [andyvorld/LGSTrayBattery#121]
Hi @andyvorld,

This error started popping up quite frequently for me these past few days.
I don't know what causes this error or when, but it happens randomly at least once a day.

Is it a known issue ?

```
LGSTrayHID.exe - System warning
Unknown Hard Error
```

**Details :** 

Mouse : G703 Lightspeed
Keyboard : G915 Wireless Mechanical
System : Windows 11 Professional 23H2 (22631.3593)

**Comment by realgooseman** [comment]
**UPDATE:** Disabling "Logitech LampArray" Service seems to fix the problem for now. Not sure what it did but it works.
Maybe worth checking that service for troubleshooting and fixing in future releases @andyvorld.

**Comment by nyakze** [comment]
Same issue with G705. Turning off Logitech LampArray Service had no effect.

**Comment by darmach** [comment]
@nyakze I would strongly encourage you to try out the fork - https://github.com/strain08/LGSTrayBattery
it's being actively developed with good velocity.
