### ISSUE TITLE
G Pro Wireless 1 showing question mark 

### ISSUE THREAD

**Issue by antiquealive** [andyvorld/LGSTrayBattery#123]
Thanks for this software, i have long dreamed Logitech to add this systray battery feature. 

**The issue**: The system tray icon shows a mouse and a battery icon, inside the battery icon is a question mark. no numeric number is displayed. Display Numeric Icon is checked. 
GPW generation 1, battery modified to 1200mah / hardware mod. 

It seems both xml get the info correctly, just now showing in system tray icon. 

**http://localhost:12321/**
'By Device ID
G Pro Wireless Gaming Mouse : [09201482-4079C08800](http://localhost:12321/device/09201482-4079C08800)
Pro Wireless Mouse : [dev00000000](http://localhost:12321/device/dev00000000)

By Device Name
[G Pro Wireless Gaming Mouse](http://localhost:12321/device/G%20Pro%20Wireless%20Gaming%20Mouse)
[Pro Wireless Mouse](http://localhost:12321/device/Pro%20Wireless%20Mouse)

LGSTray version: 3.0.3+c4b950badd60fbde23a8734d789c5a533e79ea5e'

**http://localhost:12321/device/G%20Pro%20Wireless%20Gaming%20Mouse**
'<xml>
<device_id>09201482-4079C08800</device_id>
<device_name>G Pro Wireless Gaming Mouse</device_name>
<device_type>Mouse</device_type>
<battery_percent>99.00</battery_percent>
<battery_voltage>4.18</battery_voltage>
<mileage>-1.00</mileage>
<charging>False</charging>
<last_update>06/03/2024 18:34:04 +08:00</last_update>
</xml>'

**http://localhost:12321/device/Pro%20Wireless%20Mouse**
'<xml>
<device_id>dev00000000</device_id>
<device_name>Pro Wireless Mouse</device_name>
<device_type>Mouse</device_type>
<battery_percent>100.00</battery_percent>
<battery_voltage>0.00</battery_voltage>
<mileage>63.98</mileage>
<charging>False</charging>
<last_update>06/03/2024 18:34:04 +08:00</last_update>
</xml>'

**Comment by andyvorld** [comment]
You need to select a device from the context menu under devices.

![image](https://github.com/andyvorld/LGSTrayBattery/assets/24492062/2940cb61-efd5-4ad2-8994-914ce6ae8a44)

**Comment by antiquealive** [comment]
I see, it seems somewhat a windows ui problem, whenever i move the cursor to the devices list, the list closes. 
Solved by using arrow and the enter key to make selection. it works now!
Thank you!
