### ISSUE TITLE
MX Anywhere 2 Not Detected

### ISSUE THREAD

**Issue by JustinGrote** [andyvorld/LGSTrayBattery#125]
Sorry to file an issue for a "support" item, but if this gets resolved I'll PR to the README anything that helps address this.

I've tried utilizing the LGSTray with my laptop with MX Anywhere 2 connected via bluetooth. The mouse is using native driver, I don't have logitech options or GHub installed (as my goal for using this was to remove their bloat)
![image](https://github.com/andyvorld/LGSTrayBattery/assets/15258962/ccc314c5-e91f-4b9e-a3c6-66f08a28478e)
![image](https://github.com/andyvorld/LGSTrayBattery/assets/15258962/a3740c4d-5b3f-4907-b9cc-24167a747a8c)

I fire up LGSTray and nothing shows with either devices or rediscover devices. The localhost web server doesn't see it either. I tried both standalone and framework-dependent.

```
By Device ID

By Device Name

LGSTray version: 3.0.3+c4b950badd60fbde23a8734d789c5a533e79ea5e
```

I don't see a logger in your source code or anything, what can I do to help troubleshoot this? Is G-Hub required for MX Anywhere 2 and it cannot be done native? Am I missing a driver?

**Comment by andyvorld** [comment]
Sorry using Logitech keyboard or mices via bluetooth are not supported.
This program is targetted against devices using the wireless dongles like the unifying/lightspeed range.
