### ISSUE TITLE
Working on G604 & No Startup Option

### ISSUE THREAD

**Issue by CZonin** [andyvorld/LGSTrayBattery#14]
First just wanted to say thanks for making this, it's exactly what I was looking for. I'm using it with a G604 and haven't run into any issues. It was able to identify the device and battery % automatically.

The only thing is that I saw in the changelog for the latest version that there should be an option to auto start with Windows, but i'm not seeing that on my end.

**Comment by andyvorld** [comment]
Yeah sorry, about that I think I accidentally uploaded the old binaries.
I have reuploaded the binaries at the same link.

**Comment by CZonin** [comment]
Redownloaded and the option is there now. Thanks!
