### ISSUE TITLE
Tool doesn't get device at startup

### ISSUE THREAD

**Issue by CZonin** [andyvorld/LGSTrayBattery#15]
With some of these lightspeed mice, I believe they go to sleep pretty fast after no movement is detected. I think the problem is that if the mouse goes to sleep during startup and LGSTrayBattery is set to autostart, it looses the mouse and a rescan needs to be done. Otherwise if I make sure to keep the mouse awake during startup and then LGSTrayBattery autostarts, it automatically finds the mouse and shows the battery level.

A potentially easy fix if it can't be done automatically would be to add an option to set a left click action on the tray icon, that could then be set to rescan in my case.

**Comment by andyvorld** [comment]
I have a pushed a new build with the double click to rescan.

It used to be an undocumented feature of just refreshing the battery level. Now it also performs a rescan of devices.

**Comment by CZonin** [comment]
Ah nice, good idea! I'll try it out today.

**Comment by CZonin** [comment]
Had a chance to test it earlier and it works perfectly. Thanks for adding it!
