### ISSUE TITLE
Support for Windows light theme

### ISSUE THREAD

**Issue by Xalaxis** [andyvorld/LGSTrayBattery#20]
Loving the app!

It would be great if it supported Windows light themes so that the colour of the icon was inverted during the day. Here's a screenshot of how it currently looks next to XB1ControllerBatteryIndicator.

![image](https://user-images.githubusercontent.com/12937964/134382897-34a517ee-aaa3-40c1-af03-69b53b666efc.png)

They implemented it in https://github.com/NiyaShy/XB1ControllerBatteryIndicator/issues/23 if that helps with implementation logic 🙂

**Comment by andyvorld** [comment]
I have implemented the reactive light mode, as of [v1.0.9](https://github.com/andyvorld/LGSTrayBattery/releases/tag/v1.0.9).
I don't personally use a light theme, but I think the color indicators looks fine withought anytweaks other than the black borders.

**Comment by Xalaxis** [comment]
It seems a little strange compared to the XB1-version (missing the top of the battery?), but much more visible - Thanks!

![image](https://user-images.githubusercontent.com/12937964/134939648-93824e6f-c006-42cd-92f0-3039ca2a74a9.png)
