### ISSUE TITLE
Microsoft Store release

### ISSUE THREAD

**Issue by snowtyler** [andyvorld/LGSTrayBattery#25]
Hi, is it possible to release this app on the Microsoft Store? This would be very helpful and convenient to recommend for new users.

Thanks

**Comment by andyvorld** [comment]
Currently there are no plans to get this published on the Microsoft Store.
I don't really see how publishing on to the microsoft store would help new users, as the program currently is already a single launching exe.

**Comment by snowtyler** [comment]
I just think it would be generally more user-friendly to have a one click install from the store (that automatically updates), rather than extracting a zip somewhere and having to manually check for updates. It's not really just for new users but it would be very convienent for anyone that wants to use it.
