### ISSUE TITLE
v2 Crashes after few seconds... v1 works fine

### ISSUE THREAD

**Issue by FaNt4zMa** [andyvorld/LGSTrayBattery#28]
Hey there, so first of all, a big thank you for making this tool, its greatly appreciated! I am using Logitech G Pro X Wireless headset and I was amazed that your tool supported it, but unfortunately it crashes after a few seconds. 
Tried launching it in admin, still crashes... I tried v1 and it works fine but sadly doesn't support my headset. Anyhow here's the crash report: https://pastebin.com/ArnaBse5
Could it be the version of framework I installed? I doubt it since v1 works fine... Is there a way to make v1 support my device? Also v2 is missing the poll interval features which I think is really nice, why?
Thanks a lot!!!

**Comment by FaNt4zMa** [comment]
I figured out that it crashes when it tries to rescan the device... Tried v2_0_2 and it still crashed, but after that I relaunched v2_0_5 and it didn't crash for a solid minute, then after relaunching I tried making it rescan the devices immediately and it crashed right away...

**Comment by FaNt4zMa** [comment]
FYI, I tried your other tool called LGSTrayBattery_GHUB and this one works fine, tho the icon is different, I think I'll stick with that in the meantime! Hopefully you can sort this out with your new program, I'd prefer it :)

**Comment by AlexWayfer** [comment]
[Crashlog.log](https://github.com/andyvorld/LGSTrayBattery/files/7847910/Crashlog.log)

On 2.0.5rc

**Comment by andyvorld** [comment]
Really late to this issue, but v2.0.8 changed the stack for handling the devices natively. Hopefully it had fixed your issue.
