### ISSUE TITLE
unable to have two instances running

### ISSUE THREAD

**Issue by Cowh3ad** [andyvorld/LGSTrayBattery#29]
i have two wireless logitech g devices i would like to have two instances running to show battery level of both devices, but when i try the second one closes after a while.

**Comment by andyvorld** [comment]
Real late to reply, but if you are still trying to get it to work,

Technically there can be multiple instances of the software running, you just cant have multiple instances of the webserver running.

A work around is to have two folders one with the webserver enabled in the configs, and another without.
