### ISSUE TITLE
To run this application you must install .NET.

### ISSUE THREAD

**Issue by roughnecks** [andyvorld/LGSTrayBattery#31]
HI,

why do I get this error about NET (Framework, I suppose..) for V.2 release? My Windows 10 is fully up-to-date.

**Comment by KeryaneK** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/5.0/runtime?cid=getdotnetcore

Try to download and install second option (run desktop apps) :)

**Comment by alvarokrn** [comment]
I have the same problem, running W11. I've tried to download .NET 5.0 but the link shows this:

> This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as [6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime). See our [support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) for more details.

So, I've downloaded and installed .NET v6.0 but the message 

> To run this application you must install .NET. Would you like to download it now?

is still happening.

![Captura de pantalla 2022-06-26 113632](https://user-images.githubusercontent.com/108217204/175808314-030b459a-018b-4bda-a88e-6ecccb11c2ef.png)

**Comment by CopperTiger** [comment]
I am running into this issue too. I am using windows 10. Clicking yes takes you to a .net 5 download page. I clicked to go to the .net 6 page and installed. same error. Installed the most recent sdk and still got the same error. I rebooted my system and still get the same error. I am using release 2_0_5_rc. I did download v1_0_11 and it works. Can this issue be looked into? I can provide more info upon request.

**Comment by andyvorld** [comment]
I dont have much time to work on this project anymore, but I just made a new build that only bumps the .Net version to 6 from 5.

As well as making a new framework independent build https://github.com/andyvorld/LGSTrayBattery/releases/tag/v2.0.6

**Comment by alvarokrn** [comment]
it worked! thanks @andyvorld
