### ISSUE TITLE
Complete newbie help.

### ISSUE THREAD

**Issue by Bromlin** [andyvorld/LGSTrayBattery#36]
Good day :)

Github and coding and all skills apparently needed to get this app running are lacking on me.
The downloaded zip contain a lot of file extensions, none of which I recognize or know what to do with.

There is a older version of your app which had a executable that I could run however that could not detect my mouse.
How come the latest version does not have such a file?

I am aware that this is probably a question that can not be answered without me learning about coding and HTTP and all that jazz so I understand if you refrain from answering :)

How do I go on about installing this app?

Thanks in advance :)

**Comment by paulkilla** [comment]
https://github.com/andyvorld/LGSTrayBattery/releases

Go here and download the release you want. That has the exe in it.
