### ISSUE TITLE
Enquires x2

### ISSUE THREAD

**Issue by rushden** [andyvorld/LGSTrayBattery#42]
(1) do I have to launch two copies of the app if I have got two devices? And how do I run the app on windows launch 

(2) can you please support Logitech Cordless Rumblepad 2, the reWASD software grabs the battery level, so I believe it's possible and it's Logitech

**Comment by andyvorld** [comment]
Sorry for the late comment but,

1. If you want two copies running, you need to duplicate the folder containing the program and in the copy change `serverEnable` to be `false` in the `appsettings.ini`. Auto launching on windows launch is currently bugged, and I am testing the new changes currently.

2. I am pretty sure the Logitech Cordless Rumblepad 2 uses the old HID++ 1.0 protocol and is will not be part of the software as I don't really have time to develop for the legacy protocol.
