### ISSUE TITLE
No device found after restart

### ISSUE THREAD

**Issue by Chillkroete42** [andyvorld/LGSTrayBattery#44]
Hi there,

in the previous version 2.0.8 I had the problem that the exe crashed after a reboot. In version 2.1.0 there is no device recognized and even rescanning does not help. After starting the exe manually it works and the device (mouse) it recognized correctly. Unfortunately there is no crashlog or eventlog in windows which could help :(.

Thanks in advance!
Kind regards,
David

**Comment by andyvorld** [comment]
Try the new build [v2.1.1](https://github.com/andyvorld/LGSTrayBattery/releases/tag/v2.1.1).
Tied another feature into it, so if breaks let me know and Ill remake a build without the changes.

**Comment by Chillkroete42** [comment]
So it did not work at first but after enabling/disabling it in Windows Task Manager "Autostart" it seems to work now for one device. But it seems that it is only working for one device. If i add another, only the device added last will be shown. 
Anyways, thank you very much :)
