### ISSUE TITLE
Icon disappears when hovering

### ISSUE THREAD

**Issue by elizrawr** [andyvorld/LGSTrayBattery#50]
Just installed 2.1.1 -- I opened the LGSTrayGUI.exe and the icon appears, with a ? in the battery and just sits there. When I hover, the icon disappears. 
![image](https://user-images.githubusercontent.com/18386741/204155139-237dac6f-57b4-454a-b89a-fc13a55b7ac4.png)

**Comment by elizrawr** [comment]
I'm using Logitech G435 headphones

**Comment by KH0000001** [comment]
If you right click and select "Devices", does it not show the device?

**Comment by elizrawr** [comment]
I'm not able to right click the icon since it disappears when my mouse moves over it.

**Comment by KH0000001** [comment]
Is it the same if I terminate the target process from Task Manager and restart it?

**Comment by elizrawr** [comment]
I am not able to find the process in Task Manager while the icon is showing.

**Comment by elizrawr** [comment]
I see LGSTrayGUI under Startup in Task Manager, but not in the Processes tab at any point

**Comment by KH0000001** [comment]
Maybe re-run the .exe file?
It may be affected by the fact that I haven't updated to Windows 11.

**Comment by andyvorld** [comment]
If it is the tray icon disappears on hover, that means the program crashed. Check the logs next to the .exe file and it should provide me with more info.

Are you potentially using your headset in bluetooth mode? As that may not work.

The last resort is setting `appsettings.ini` to,
```
[DeviceManager]
GHUB = true
HID_NET = false
Native = false
```

And use the program with Logitech G Hub.

Sorry, I don't have much time on my hands lately to fix this program up further.

**Comment by elizrawr** [comment]
I'm on Windows 10 Education edition. I checked event logs, this is what I found. 
![image](https://user-images.githubusercontent.com/18386741/207171233-7465b8f0-72bd-4e14-aad6-1a25e9547974.png)

**Comment by elizrawr** [comment]
Some success. I changed the appsettings.ini and opened with Logitech and I can now interact with the icon. I see my G435 headphones under the Devices drop-down, however when I hover it says "G435 0.00%". I restarted my PC just in case and am still seeing it. Thanks for all the help everyone.
