### ISSUE TITLE
Wake up logitech devices?

### ISSUE THREAD

**Issue by pickonedev** [andyvorld/LGSTrayBattery#56]
Hi!

There is any way to wake up sleeping devices? 
I use my headsets once per week and when the device it is sleeping, I won't get any battery status. There is any way in order to wake up the device every time I startup my computer?

Thank you!

**Comment by pickonedev** [comment]
@andyvorld Any idea or advice?

Thanks!

**Comment by andyvorld** [comment]
I am not really sure, I would have to dig into the protocol to find out more.

Could you check if logitech g hub is able to see the battery while the headset is sleeping? As if G hub it self cant do it, then I would not be able to either.

**Comment by pickonedev** [comment]
That is the problem :-(
G Hub won't see the battery while any device it is sleeping. Keyboard, mouse, headset, nothing when sleeping...
