### ISSUE TITLE
Feature Request: Overlay

### ISSUE THREAD

**Issue by Pesoen** [andyvorld/LGSTrayBattery#59]
is it possible to get an overlay similar to the one this program makes?
https://github.com/mx0c/Corsair-Headset-Battery-Overlay

decided to switch to logitech, since the battery was getting bad, buttons stopped working and other things started to annoy me about my corsair headset. and right now, this is the only thing i really miss to commit to the G933 i now have. i use it mostly to have a battery indicator when i am in vr, so having this display option would be really cool.

it does not have to be a 1:1 replica of this apps way to display, but just some way to display the battery level in text on the desktop, displaying over other apps would be amazing, and the last push i need to fully ditch my Corsair headset.

Battery life is amazing though, where i would have about 15-20% battery on my corsair headset, i still have 70% on the logitech headset, and it has some much needed buttons so i can control playback when i walk around the house.

**Comment by andyvorld** [comment]
Yeah sorry but overlays are out of scope as there will be too many use cases that I would have to account for.

However, the `Http/Web "server" api` exposes the ability to create your own overlay in rainmeter or any other UI interface.

Quick and dirty example, rainmaker skin targetting G HUB device "dev00000000"; (No support will be given to this)
![image](https://user-images.githubusercontent.com/24492062/230581572-16719668-8218-47f3-ba1d-098e2af2e90a.png)
[Example_0.zip](https://github.com/andyvorld/LGSTrayBattery/files/11177713/Example_0.zip)
