### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Milchkarl** [andyvorld/LGSTrayBattery#62]
1. It would be nice to have it autostart in multiple instances to display the pcerentages of multiple devices like in hwinfo system tray displays.
2. After selecting which of the devices should be displayed the program should remember the selection and make use of it during autostart so it does not need to be selected everytime the program restarts.

**Comment by andyvorld** [comment]
Feature is in v3, https://github.com/andyvorld/LGSTrayBattery/releases/tag/v3.0.0-rc.2
