### ISSUE TITLE
Suggestion: Rainmeter support

### ISSUE THREAD

**Issue by neuralnermal** [andyvorld/LGSTrayBattery#71]
This would be amazing as a rainmeter skin, so users can just glimpse over their 2nd monitor to check battery instead of hovering it on the system tray.
Also I can confirm this works well with MX master 3S
![image](https://github.com/andyvorld/LGSTrayBattery/assets/132416432/047f20cf-e982-49c7-80e9-85c025031b9d)

**Comment by andyvorld** [comment]
There is support for integration into rainmeter as seen in https://github.com/andyvorld/LGSTrayBattery/issues/59#issuecomment-1500106065, via the http webserver option.

The creation and maintenance of an actual rainmeter widget however is out of scope of this project.
