### ISSUE TITLE
Showing double icon when restarting explorer.exe

### ISSUE THREAD

**Issue by ShirowLeBG** [andyvorld/LGSTrayBattery#88]
Hello,

I have some problems with my explorer on my PC, so quite frequently, I have to restart it
Unfortunately, when i do so, the icon in the taskbar is shown 2 times :
![image](https://github.com/andyvorld/LGSTrayBattery/assets/61913454/ee039022-b60d-4501-a172-31ca09023652)

The two are linked, so when I close one, the other close too

Can you do something ?

Thanks

**Comment by IIIdefconIII** [comment]
check if it has the same device idea on the localhost:12321 page, if it isnt maybe hide it
