### ISSUE TITLE
Improvement development

### ISSUE THREAD

**Issue by IIIdefconIII** [andyvorld/LGSTrayBattery#89]
Can the app get a shortcut link? So whenever i click it, it automaticly open the in my case "c:\program files\lghub\lghub.exe"

Then i can get rid of the extra Logitech G HUB shortcut in here:
The options i got is systrax, cause this launcher launches the systray icons.
So that open LGS link should be set on the systray, cause the app is limited by editing the context menu there,

![image](https://github.com/andyvorld/LGSTrayBattery/assets/9917659/5ef78a5f-b55c-441e-9b2e-a4fe312a2b4f)
The properties window of the second pictiue is from a normal shortcut instead of a systray icon.

![image](https://github.com/andyvorld/LGSTrayBattery/assets/9917659/476368b1-30d5-49b2-82f1-707346b555d9)

Total sneak prev:
![image](https://github.com/andyvorld/LGSTrayBattery/assets/9917659/67fa404d-911c-43c8-82e9-7b9cda451a92)

**Comment by IIIdefconIII** [comment]
2 months later, not a single reaction?

**Comment by tr4npt** [comment]
There's no installer, so this is an essentially "portable" app.  Just create a shortcut yourself.  Copy LGSTray.exe from Explorer and then right-click in the folder where you want it and select "Paste shortcut" from the context menu.

**Comment by IIIdefconIII** [comment]
nice the new version has really nice improvements
