### ISSUE TITLE
Webserver returns NS_ERROR_NET_RESET

### ISSUE THREAD

**Issue by Sjorsa** [andyvorld/LGSTrayBattery#94]
I set `addr` to `"0.0.0.0"` as instructed by the README, the app itself works great, I can see the battery level in the tray, but the webserver isn't working, it responds with NS_ERROR_NET_RESET when I go to http://my_ip:12321/

My configuration:
```
[UI]
enableRichToolTips = true

[HTTPServer]
enabled = true
addr = "0.0.0.0"
port = 12321

[GHub]
enabled = true

[Native]
enabled = true

# Time in seconds to retry a device poll on failure
retryTime = 10

# Time in seconds to next device poll on sucess
pollPeriod = 600

# List of disabled devices
disabledDevices = [
]
```

**Comment by andyvorld** [comment]
Thanks for the pickup, I changed the backend during the upgrade to v3. 

The new IP address for bind all should be "*", instead of "0.0.0.0".

**Comment by Sjorsa** [comment]
That fixes it, great!
